version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.14"
  apt_packages:
    - curl
  jobs:
    build:
      pdf:
        - mkdir -p "$READTHEDOCS_OUTPUT/pdf/"
        - curl -LO https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz
        - tar xvfa typst-*.tar.xz && mv typst-*/typst . && rm -rf typst-*
        - make -C docs typst
        - ./typst compile docs/_build/typst/main/main.typ "$READTHEDOCS_OUTPUT/pdf/main.pdf"

formats:
  - pdf

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

sphinx:
  configuration: docs/conf.py
